### ISSUE TITLE
可以加一个功能给推荐人分类，independent 和 dependent

### ISSUE THREAD

**Issue by iphyer** [xiaohk/recrec#1]
可以加一个功能给推荐人分类，independent 和 dependent。

如果和你在一起发表论文，按照 USCIS 的标准就不是 independent，可以去掉。

**Comment by xiaohk** [comment]
谢谢！现在有支持exclude collaborator这个filter，用了以后就隐藏所有和你一同发过文章的人。这个功能和你说的一样吗？真正的independent好像还不能有在一个机构工作过，但是这些info比较难query。

<img width="216" alt="image" src="https://github.com/xiaohk/recrec/assets/15007159/38f460ea-faee-4b0d-ad06-ecd31a47c54f">

**Comment by iphyer** [comment]
是的，agree，需要去分辨文章上下标，这个就可以了，去掉合作者。
赞！👍
